### PR TITLE
React UI tweaks

### PR DESCRIPTION
**Pull request by ancorgs**
Two UI improvements:

- Manage the focus by clicking on the whole preview area of the participant in the roster, not necessarily in the video element. Removing the focus becomes possible again.
- Add buttons to toggle video and audio in the header. 

Screenshot from 2023-02-03 16-08-42

### CODE REVIEW

**Comment by ancorgs** [comment]
This should fix #392

**Comment by ancorgs** [comment]
It looks much better with the new commits from @dgdavid. But I think the toggle chat look&feel could be more consistent with the mute/video ones.

**Comment by ancorgs** [comment]
LGTM, in any case, after the changes.

**Comment by dgdavid** [comment]
> It looks much better with the new commits from @dgdavid. But I think the toggle chat look&feel could be more consistent with the mute/video ones.

Consistency is a bit tricky here. At least from my point of view.

The reason is that I see at them as different group of toggle actions. For the mic and camera, we want to visually communicate that they are on or off, using the green color for the icons when active and the red color for the background when inactive. Hopefully, this can help the user to quickly realize the state of those inputs. In the case of the chat… we don't matter if you wanted to read it or not. It just uses the white background when active…

But sure, in next rounds we can think about it and bring a better solution in the shake of consistency.

**Review by dgdavid — APPROVED** [review]

**Pull request merged**
