### PR TITLE
Update Jangouts to run with latest Janus-gateway

### PR DESCRIPTION
**Pull request by code-master5**
This PR can be considered as a major step towards solving the #187 issue.

### CODE REVIEW

**Comment by code-master5** [comment]
I have updated the `bower.json` to run with Janus-gateway (up till the janus commit - https://github.com/meetecho/janus-gateway/commit/0ce774d4d2eb2b44d771b77b099183aae07857e9).

This PR is a result of [this](https://groups.google.com/forum/#!topic/meetecho-janus/VNJbMgsGPW0) conversation with Janus-gateway maintainers.

**Comment by code-master5** [comment]
@imobachgs @ancorgs We are quite close to our aim of updating Jangouts (master-branch) to support latest Janus (at least up to this [commit](https://github.com/meetecho/janus-gateway/commit/cabe80ea35c76b36d3180b4f7063d60fa728548d) ). 

This PR updates Jangouts to support Janus-gateway (up to commit done on [Feb 27](https://github.com/meetecho/janus-gateway/commit/0ce774d4d2eb2b44d771b77b099183aae07857e9))

**Comment by code-master5** [comment]
@imobachgs @ancorgs 
One thing more. Currently, I'm trying to update Jangouts to run with more latest Janus-gateway changes.

After some chat with Janus maintainers, I've come to know that after the commits done on Feb 27 in Janus-gateway repo, `some methods exposed by the janus.js library have changed`. So, I guess I'll have to look into latest `janus.js` and Janus API documentation for accommodating these changes in Jangouts.

Some progress in this regard can be seen [here](https://groups.google.com/forum/#!topic/meetecho-janus/dAWVrD4IdXQ).

**Comment by code-master5** [comment]
It's sad that even after merging this PR, #182 still can't be merged. I was sooo... close. But I'm trying!

**Comment by code-master5** [comment]
@ancorgs Now you can merge this PR for latest janus support. Please checkout PR #182 , after merging this.

**Comment by ancorgs** [comment]
I think this pull request fixes the adapter.js issue in the wrong place (Jangouts instead of Janus). I have prepared this pull request to fix things for everybody https://github.com/meetecho/janus-gateway/pull/917

I hope to release a new version with the proper dependencies fixed on Monday (Janus folks are usually fast as lightning accepting patches).

**Comment by code-master5** [comment]
@ancorgs Even better! I should've considered that myself. One more thing - the config object now requires `data: true` for chat message communication, which this PR fixes for jangouts. Is this something that should be corrected in Janus??

**Comment by code-master5** [comment]
@ancorgs Now I removed adapter dependency..

**Comment by ancorgs** [comment]
I'm having problems to make the data channel work in Firefox 52.1.1 with the latest Janus (compiled from the master branch of the repository). Even with your suggested changes it does not work. I will need further debugging.

**Comment by ancorgs** [comment]
At some point I get `'State change on data channel: null'. I does not happen with old versions of Janus. Most likely the culprit is the commit you already mentioned in your question to the Janus Google group (I have not verified that), but your fix (adding `data: true`) makes no difference to me.

**Comment by code-master5** [comment]
@ancorgs I guess I have found what's happening. The `createOffer` in `pluginHandle` object has `data: false`, by default. See updated API here - here https://janus.conf.meetecho.com/docs/JS.html. 

Now, I've done the required chages to this PR and I'm also getting -
`State change on data channel: open`

**Comment by ancorgs** [comment]
@code-master5 Yes. I also have (almost exactly) the same change prepared. Looks like we were doing the same at the same time. :wink: I tested it and everything seems to work.

It took me quite some time because recent versions of Janus break Jangouts with Firefox. I found the [offending commit](https://github.com/meetecho/janus-gateway/commit/db66959e4e462a3185f8f64ebd2fb5e5d014f0b2) and I will report the problem to Janus developers.

So looks like everything is cleared up for a new release of Jangouts... as long as it's used with a Janus gateway older than that commit (April 28th). I will do the release today... after RealWorkImPaidFor(TM). 😄

**Comment by code-master5** [comment]
@ancorgs This is exciting! I'll get to work with newer version of Jangouts. Also now we can have Pin Rooms... 😉

**Comment by ancorgs** [comment]
Closed in favor of #193

**Pull request closed without merging**
