### PR TITLE
Fixes startHidden feature

### LINKED ISSUE #48: Regression: Start hidden feature doesn't work
Introduced by me in 0a22c8545421c276d7c12e75d07898009d607085

### PR DESCRIPTION
**Pull request by ChrisBr**
The startHidden feature didn't worked! Introduced in 0a22c8545421c276d7c12e75d07898009d607085.
Fixes #48

### CODE REVIEW

**Comment by ChrisBr** [comment]
@ancorgs @imobach Please review! I've broken this in my URL params PR...

**Comment by ancorgs** [comment]
That feature was a recording experiment that nobody is currently using. No
big deal

**Comment by imobach** [comment]
I'd also consider dropping this feature. Thoughs?

**Comment by ancorgs** [comment]
As said, it's only there to support an unfinished recording experiment. I don't see a good reason to keep it in master (we can bring it back in a separate branch if we resurrect the recording experiments). And I don't like the way it pollutes the nice urls.

So... kill it!

**Comment by imobach** [comment]
Yeah, I like the idea of keeping it in a different branch.

**Comment by ancorgs** [comment]
And it's already kept in a different branch as long as @ChrisBr does not delete https://github.com/ChrisBr/jangouts/tree/ui-params :smile:

**Comment by ChrisBr** [comment]
@ancorgs @imobach thanks for the information! I can keep the branch in my fork or I could also push the branch to the main repo, what would you prefer?

**Comment by imobach** [comment]
@ChrisBr I think it's better to push the branch to the main repo. Thanks!

**Comment by ChrisBr** [comment]
@imobach okay, will do!

**Pull request closed without merging**
