### PR TITLE
Fix Angular 2 version

### PR DESCRIPTION
**Pull request by imobachgs**
This is the first attempt to make the application work with Angular JS 2.4.0. It's still a work in progress, but I expect the application to boot.

### CODE REVIEW

**Comment by imobachgs** [comment]
The testsuite is running again. This PR does not solve the issues listed in #156 but, at least, we have something to start working with.

**Comment by imobachgs** [comment]
I've enabled Travis to run our unit tests (and they're green :) ).

**Comment by ancorgs** [comment]
LGTM

**Comment by imobachgs** [comment]
Thanks!

**Pull request merged**
